site_name: lernOS Content Curation Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen: 1-0-Grundlagen.md
    - Lernpfad:
      - Ãœbersicht: 2-0-Lernpfad.md
      - Woche 0: 2-1-Woche-0.md
      - Woche 1: 2-2-Woche-1.md
      - Woche 2: 2-3-Woche-2.md
      - Woche 3+4: 2-4-Woche-3-4.md
      - Woche 5: 2-6-Woche-5.md
      - Woche 6: 2-7-Woche-6.md
      - Woche 7: 2-8-Woche-7.md
      - Woche 8: 2-9-Woche-8.md
      - Woche 9: 2-10-Woche-9.md
      - Woche 10: 2-11-Woche-10.md
      - Woche 11: 2-12-Woche-11.md
      - Woche 12: 2-13-Woche-12.md
    - Anhang: 3-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-content-curation/blob/master/de/lernOS-Content-Curation-Guide-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-content-curation/blob/master/de/lernOS-Content-Curation-Guide-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-content-curation/blob/master/de/lernOS-Content-Curation-Guide-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-content-curation/blob/master/de/lernOS-Content-Curation-Guide-de.epub
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-content-curation'
repo_url: 'https://github.com/cogneon/lernos-content-curation'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom
    alternate:
         - name: English
           link: https://cogneon.github.io/lernos-content-curation/en
           lang: en

plugins:
  - search
